Set slacks to zero
project-pareto/project-pareto pull request #117
Opened 2022-04-06 01:22 UTC by Andresj89

## Fixes/Addresses/Summary/Motivation:

This PR adds a method to set slacks to zero for the strategic model. The method checks if the termination condition of the solver is unfeasible, in that case the slacks are activated and the model is run again.

## Changes proposed in this PR:
- The `run_strategic_model.py` has been simplified. It now contains call to the method `solve_model(model, options)` which receives a model object and a dictionary with the following options: 
```
options = {
    "deactivate_slacks": True,
    "scale_model": True,
    "scaling_factor": 1000000,
    "running_time": 60,
    "gap": 0,}
```
### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my
contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md file
   at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has
   rights to intellectual property that includes these contributions, I represent that I have
   received permission to make contributions and grant the required license on behalf of that
   employer.

2022-04-11 20:59 UTC, NienkeWagenaar requested changes

2022-04-11 20:59 UTC, NienkeWagenaar commented on pareto/strategic_water_management/strategic_produced_water_optimization.py
> +
Can we move the unfixing to before the if-statement?

2022-04-12 15:14 UTC, melody-shellman requested changes
Overall looks good. I like this new restructuring of code, it is definitely cleaner. I ran the code with our four modes (capacity vs distance, input vs calculated) and all outputs looked good! Only change suggested is to remove df_parameters as an input to  **_preprocess_data (line 5212)**, similar to the other methods.

2022-04-12 15:14 UTC, melody-shellman commented on pareto/strategic_water_management/strategic_produced_water_optimization.py
>          for index in var:
We are still rounding small values to 0 when fixing variables prior to solving water quality. I quickly tested removing this rounding and the model is infeasible -- this is something I plan to address in a future PR.

2022-04-15 19:17 UTC, NienkeWagenaar submitted a review, later dismissed

2022-04-15 19:17 UTC, NienkeWagenaar commented
I removed two other unused imports. Other than that it looks good!

2022-04-19 18:15 UTC, melody-shellman submitted a review, later dismissed
Looks good, thanks for implementing those suggestions!

2022-04-20 13:37 UTC, melody-shellman approved these changes
Looks good, runs as expected.

2022-04-21 16:43 UTC, NienkeWagenaar approved these changes
Looks great!

2022-04-21 18:49 UTC, merged