Convert docs for operational model to ASCII LaTeX
project-pareto/project-pareto pull request #159
Opened 2022-09-13 17:20 UTC by lbianchi-lbl

## Supersedes: #140 

## Changes proposed in this PR:

- Convert Unicode characters to ASCII LaTeX for operational model only

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my
contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md file
   at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has
   rights to intellectual property that includes these contributions, I represent that I have
   received permission to make contributions and grant the required license on behalf of that
   employer.

2022-09-13 20:19 UTC, tarnold17 requested changes
Some further changes are needed. I have also provided some optional suggestions.

2022-09-13 20:19 UTC, tarnold17 commented on docs/model_library/operational_water_management/index.rst
> +**Completions Pad Demand Balance:** :math:`\forall p \in CP, t \in T`
```suggestion
**Completions Pad Demand Balance:** :math:`\forall \textcolor{blue}{p \in CP}, \textcolor{blue}{t \in T}`
```

If you want extra credit, you can add color to all of these statements like we have done in the strategic model documentation.

2022-09-13 20:19 UTC, tarnold17 commented on docs/model_library/operational_water_management/index.rst
For more extra credit, you can change line 427 to

    **Completions Pad Processing Capacity:** :math:`\forall \textcolor{blue}{p \in CP}, \textcolor{blue}{t \in T}`

2022-09-13 20:19 UTC, tarnold17 commented on docs/model_library/operational_water_management/index.rst
> +where :math:`\textcolor{green}{\varepsilon^{Treatment}}` \le 1
```suggestion
where :math:`\textcolor{green}{\varepsilon^{Treatment}} \leq 1`
```

2022-09-13 20:19 UTC, tarnold17 commented on docs/model_library/operational_water_management/index.rst
> +where :math:`\textcolor{green}{\varepsilon_{r,w}^{Treatment}}` \le 1
```suggestion
where :math:`\textcolor{green}{\varepsilon_{r,w}^{Treatment}} \leq 1`
```

2022-09-13 20:19 UTC, tarnold17 commented on docs/model_library/operational_water_management/index.rst
>  .. _model_terminology:
For more extra credit, change line 981 to

    :math:`[\textcolor{blue}{t}]` **or** :math:`[\textcolor{blue}{t \in T}]` **:** This notation indicates that timing of capacity expansion has not yet been implemented.

2022-10-25 18:34 UTC, lbianchi-lbl commented
@tarnold17 Thanks once again for all your review comments. I think I've addressed everything except for the "extra credit". If that's OK, feel free to re-review in case I missed something directly related to the ASCII-fication, and we can merge this PR in.

2022-10-25 20:34 UTC, tarnold17 commented on docs/model_library/operational_water_management/index.rst
> +    min \ \textcolor{red}{C^{TotalSourced}}+\textcolor{red}{C^{TotalDisposal}}+\textcolor{red}{C^{TotalTreatment}}+\textcolor{red}{C^{TotalCompletionsReuse}}+
```suggestion
    \min \ \textcolor{red}{C^{TotalSourced}}+\textcolor{red}{C^{TotalDisposal}}+\textcolor{red}{C^{TotalTreatment}}+\textcolor{red}{C^{TotalCompletionsReuse}}+
```

2022-10-25 20:38 UTC, lbianchi-lbl commented on docs/model_library/operational_water_management/index.rst
> +    min \ \textcolor{red}{C^{TotalSourced}}+\textcolor{red}{C^{TotalDisposal}}+\textcolor{red}{C^{TotalTreatment}}+\textcolor{red}{C^{TotalCompletionsReuse}}+
Good eye, thanks. Fixed

2022-10-25 20:40 UTC, tarnold17 submitted a review, later dismissed

2022-10-25 21:58 UTC, merged