treatment document
project-pareto/project-pareto pull request #229
Opened 2023-03-28 17:56 UTC by ElmiraShamlou

## Fixes/Addresses/Summary/Motivation:

Added water treatment documentation

## Changes proposed in this PR:
- added description to treatment modeling including removal efficiency, treatment efficiency, balances, and costing methods 
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my
contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md file
   at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has
   rights to intellectual property that includes these contributions, I represent that I have
   received permission to make contributions and grant the required license on behalf of that
   employer.

2023-04-03 22:37 UTC, tarnold17 requested changes
I like the content here! I know I left a lot of comments, but most of them are fairly minor things like formatting suggestions and typo fixes. I do, however, have a broader comment that I want to make. When giving the overview of treatment modeling within PARETO, this document speaks of PARETO in general terms. However, in reality, a lot of these ideas are only relevant to the strategic model, and not to the operational model, because component removal has not been implemented for the operational model. So, I think it is potentially confusing for the reader how some of this content relates to PARETO as a whole, and so we should consider if there is a better way we can explain that at the beginning of this page.

I also think it would be helpful to get multiple reviews of this content, and it would probably be helpful to discuss over a call, and not just through GitHub comments. @melody-shellman, @MAZamarripa, what do you think of that?

2023-04-03 22:37 UTC, tarnold17 commented on docs/model_library/water_treatment/index.rst
> +Thermodynamic Relations
```suggestion
**Thermodynamic Relations**
```
To distinguish it from the surrounding content, I think that "Thermodynamic Relations" should be written in bold text.

2023-04-03 22:37 UTC, tarnold17 commented on docs/model_library/water_treatment/index.rst
> +Design Equations:
```suggestion
**Design Equations**
```
Same comment here - I think this should be bold. And drop the colon to be consistent.

2023-04-03 22:37 UTC, tarnold17 commented on docs/model_library/water_treatment/index.rst
> +Thermodynamic Relations
```suggestion
**Thermodynamic Relations**
```

2023-04-03 22:37 UTC, tarnold17 commented on docs/model_library/water_treatment/index.rst
> +Design Equations:
```suggestion
**Design Equations**
```

2023-04-03 22:37 UTC, tarnold17 commented on docs/model_library/water_treatment/index.rst
> +Thermodynamic Relations
```suggestion
**Thermodynamic Relations**
```

2023-04-03 22:37 UTC, tarnold17 commented on docs/model_library/water_treatment/index.rst
> +Design Equations
```suggestion
**Design Equations**
```

2023-04-03 22:37 UTC, tarnold17 commented on docs/model_library/water_treatment/index.rst
> +Annualization factor: The annualization factor for CAPEX is calculated based on fractional interest rate $r = 0.1$ per year and amortization period $y = 10$ years.
```suggestion
Annualization factor: The annualization factor for CAPEX is calculated based on fractional interest rate :math:`r = 0.1` per year and amortization period :math:`y = 10` years. 
```

2023-04-17 17:35 UTC, tarnold17 requested changes
I have left a few new comments, and I unresolved a few old comments that I don't think were completely addressed. However, everything that remains to address is very minor. This is awesome work and it is very close to being ready to merge!

2023-04-17 17:35 UTC, tarnold17 commented on docs/model_library/water_treatment/index.rst
> +   LRA = \{(l, r) \in LLA | r \in R\}
```suggestion
   LRA = \{(l, r) \in LLA \ | \ r \in R\}
```
I'm picking a nit here, but this will look better with some spaces added.

2023-04-17 17:35 UTC, tarnold17 commented on docs/model_library/water_treatment/index.rst
> +   LRT = \{(l, r) \in LLT | r \in R\}
```suggestion
   LRT = \{(l, r) \in LLT \ | \ r \in R\}
```
Same comment here.

2023-04-17 17:35 UTC, tarnold17 commented on docs/model_library/water_treatment/index.rst
Another nitpick, and I should have noticed this on my first review. I recommend changing the variables in the figure to have "feed", "treated", and "residual" as superscripts rather than subscripts to match the formatting of the variables in the body of the page.

![image](https://user-images.githubusercontent.com/26798258/232560569-ed0c8798-406a-4131-8716-11c321ab405f.png)

2023-04-17 17:35 UTC, tarnold17 commented on docs/model_library/2022_10_31_206_017_PWTreatment_Technology_matrix.xlsx
@ElmiraShamlou I still see a column of Box links in the "Literature" tab of the treatment matrix Excel file. Can you please remove that column?

2023-04-17 17:35 UTC, tarnold17 commented on docs/model_library/water_treatment/index.rst
> +| :ref:`Mechanical_vapor_recompression_model`            |
@ElmiraShamlou at this point I only see "MVC" in the page and not "MVR". However, I see instances of both "mechanical vapor compression" and "mechanical vapor recompression". Can you please change all instances of "mechanical vapor recompression" to "mechanical vapor compression"?

2023-04-17 17:35 UTC, tarnold17 commented on docs/model_library/water_treatment/index.rst
> +Single effect evaporation and multi effect evaporation has been studied for shale water desalination. Mechanical vapor recompression, uses a compressor to utilize the heat from the evaporated vapor f
```suggestion
Single effect evaporation and multi-effect evaporation has been studied for shale water desalination. Mechanical vapor recompression, uses a compressor to utilize the heat from the evaporated vapor for further evaporation. As shown in the schematic in Figure (2), for a system with I effects, the produced water is fed into evaporator I. After evaporation, the brine from the i\ :sup:`th` effect is sent to the (i-1)\ :sup:`th` effect and the vapor from the (i-1)\ :sup:`th` effect is sent to the i\ :sup:`th` effect.
```
Hyphenate "multi-effect" to be consistent.

2023-04-17 17:35 UTC, tarnold17 commented on docs/model_library/water_treatment/index.rst
> +Model Description
Another part of the page had been modified to clarify that the MVC model is currently under development, so I am resolving this comment.

2023-04-18 15:55 UTC, melody-shellman approved these changes
Looks great! I agree with the few remaining items that Travis outlined, but overall great work! It was definitely time to build out documentation entirely dedicated to treatment. This will be a good standard to hold when we move to beneficial reuse work soon :)

2023-04-18 20:25 UTC, melody-shellman approved these changes
LGTM

2023-04-18 21:06 UTC, tarnold17 approved these changes

2023-04-18 21:35 UTC, merged