Pipeline Config Options
project-pareto/project-pareto pull request #89
Opened 2021-11-19 21:59 UTC by melody-shellman

## Notes
This PR Addresses Issue #88 . 
There are four possible configuration scenarios:

1. User inputs pipeline capacity, pipeline cost is based on capacity
2. User inputs pipeline capacity, pipeline cost is based on distance
3. pipeline capacity is calculated, pipeline cost is based on capacity
4. pipeline capacity is calculated, pipeline cost is based on distance

These four scenarios are handled with two config variables: "pipeline_capacity" and "pipeline_cost"

Note that this PR does not include error handling. For now, a user must include input tabs for all 4 scenarios. Error handling will be in a separate issue. 

## Testing
![image](https://user-images.githubusercontent.com/91741082/142696433-6aede796-704b-404a-a945-4edac43dff1c.png)

2021-12-10 23:00 UTC, NienkeWagenaar requested changes
I think we shouldn't upload the results into GIT, as it may cause confusion. I'll add it as discussion item for our coordination meeting.

2021-12-10 23:02 UTC, NienkeWagenaar commented
I don't get results for the settings:
Pipeline cost = capacity based
Pipeline capacity = input

When using the layflat input file and running for 1200 seconds. Could someone with a Gurobi solver try this out?

2021-12-13 20:54 UTC, drouvenm commented
@NienkeWagenaar I ran this branch with the layflat input file, the pipeline_cost set to capacity_based and the pipeline_capacity set to input. It solved fine for me and Gurobi got to a 6% gap after 60 seconds. Is that helpful to you?

2021-12-13 22:37 UTC, NienkeWagenaar commented
> 

@drouvenm, yes that's very helpful, thank you! Do the results make sense? I could have a look at the Excel file, if you like.

2021-12-14 00:46 UTC, Andresj89 commented
From my tests I think the calculation of capex using `capacity_based` look good. However, for `distance_based` I'm getting strange results. I get the following:
```
Disposal Fraction Produced Water = [%] = 100.00000000000003
Fresh Fraction Completions Demand = [%] = 99.99999999999974
```
I reduced the pipeline Capex in the objective function: `model.v_C_PipelineCapEx*0.1` and `model.v_C_PipelineCapEx*0.01`, but the disposal fraction and fresh water demand was still 100%. I checked the calculation of capacity based on diameters and it is correct.

Also, I think parameter `model.p_mu_Pipeline` should be checked with a CONFIG option too. If the user wants to input capacities and usd/bbl only, then there is no need to provide diameters.

2021-12-20 17:34 UTC, NienkeWagenaar commented
> > 
> 
> @drouvenm, yes that's very helpful, thank you! Do the results make sense? I could have a look at the Excel file, if you like.

I confirm the results in the Excel file makes sense. We'll need to discuss the follow up related to the distance_based solutions.

2021-12-20 17:35 UTC, NienkeWagenaar approved these changes

2021-12-21 22:22 UTC, MAZamarripa requested changes
looks good
minor comments/changes

2021-12-21 22:22 UTC, MAZamarripa commented on pareto/tests/test_strategic_model.py
> +    # assert pytest.approx(380699650.6, abs=1e-1) == pyo.value(m.v_Z)
this should not be a comment

2021-12-21 22:22 UTC, MAZamarripa commented on pareto/tests/test_strategic_model.py
> +    # assert pytest.approx(380699650.6, abs=1e-1) == pyo.value(m.v_Z)
We need to test all the options

2022-03-02 21:03 UTC, Andresj89 approved these changes
This looks good.

2022-03-08 00:04 UTC, NienkeWagenaar approved these changes
Looks great!

2022-03-08 23:28 UTC, MAZamarripa approved these changes

2022-03-08 23:29 UTC, MAZamarripa approved these changes
lgtm

2022-03-08 23:45 UTC, merged